# -*- coding: utf-8 -*-
"""Build a focused, self-contained dashboard for state_mcts_report.json."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
from pathlib import Path


HTML_TEMPLATE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>State MCTS experiments</title>
<style>
:root{color-scheme:dark;--bg:#0b1016;--panel:#121a24;--panel2:#172231;--line:#29394d;--text:#e7edf5;--muted:#91a2b7;--blue:#62b0ff;--green:#55d69e;--red:#ff7185;--yellow:#f6c85f}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,sans-serif}.page{max-width:1320px;margin:auto;padding:32px 30px 70px}h1{font-size:29px;margin:0 0 4px}h2{font-size:20px;margin:30px 0 12px}.sub{color:var(--muted);margin-bottom:22px}.callout{border-left:3px solid var(--blue);padding:10px 14px;background:#111c28;color:#c7d6e7;border-radius:0 8px 8px 0;margin:16px 0 22px}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}.card,.run-card{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:15px}.card h3{margin:0 0 5px;color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.06em}.big{font-size:26px;font-weight:750}.badge{display:inline-block;padding:3px 8px;border-radius:999px;background:#26364a;color:#c9d6e5;font-size:12px}.good{background:#173c31;color:var(--green)}.bad{background:#46232c;color:var(--red)}.warn{background:#463a1d;color:var(--yellow)}
.folder-manager,.rename-list,.bulk-toolbar{background:var(--panel);border:1px solid var(--line);border-radius:12px;overflow:hidden}.folder-toolbar,.bulk-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 14px}.folder-toolbar{border-bottom:1px solid var(--line)}.bulk-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.folder-row{display:grid;grid-template-columns:minmax(180px,1fr) auto auto auto;gap:8px;align-items:center;padding:9px 14px;border-bottom:1px solid var(--line)}.folder-row:last-child{border-bottom:0}.folder-input,.name-input,.folder-select{width:100%;padding:8px 10px;border:1px solid var(--line);border-radius:7px;background:#0c131c;color:var(--text)}.bulk-actions .folder-select{width:auto;min-width:150px}.folder-action,.save-name{padding:8px 11px;border:1px solid #3b6e9f;border-radius:7px;background:#17314a;color:#dcecff;cursor:pointer}.folder-action:hover,.save-name:hover{background:#204566}.folder-action:disabled{opacity:.45;cursor:not-allowed}.folder-action.danger{border-color:#70404a;background:#3b2028}.rename-row{display:grid;grid-template-columns:auto minmax(190px,1fr) minmax(190px,2fr) minmax(130px,180px) auto minmax(70px,auto);gap:10px;align-items:center;padding:11px 14px;border-bottom:1px solid var(--line)}.rename-row:last-child{border-bottom:0}.run-select{width:17px;height:17px;accent-color:var(--blue);cursor:pointer}.rename-id{overflow:hidden;text-overflow:ellipsis;color:var(--muted);font:12px ui-monospace,SFMono-Regular,Menlo,monospace}.save-status{font-size:12px;color:var(--muted)}
.comparison{background:var(--panel);border:1px solid var(--line);border-radius:12px;overflow:hidden}.comparison-row{display:grid;grid-template-columns:minmax(190px,300px) 1fr 75px;align-items:center;gap:14px;width:100%;padding:13px 15px;border:0;border-bottom:1px solid var(--line);background:transparent;color:var(--text);text-align:left;cursor:pointer}.comparison-row:last-child{border-bottom:0}.comparison-row:hover,.comparison-row:focus{background:var(--panel2);outline:0}.run-name{font-weight:700;overflow:hidden;text-overflow:ellipsis}.models{font-size:12px;color:var(--muted)}.track{height:18px;background:#223044;border-radius:6px;position:relative;overflow:visible}.mean-bar{height:100%;background:linear-gradient(90deg,var(--blue),var(--green));border-radius:6px}.range{position:absolute;top:7px;height:3px;background:var(--yellow)}.range:before,.range:after{content:"";position:absolute;top:-4px;width:2px;height:11px;background:var(--yellow)}.range:before{left:0}.range:after{right:0}.score{text-align:right;font-size:18px;font-weight:750}
.folder-block{margin:9px 0}.folder-summary{display:flex;align-items:center;gap:9px;padding:3px 1px;font-size:16px}.folder-block[open]>.folder-summary{margin-bottom:12px}.folder-badge{display:inline-block;padding:2px 8px;border-radius:999px;background:#26364a;color:#c9d6e5;font-size:11px}.run-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(390px,1fr));gap:14px}.run-card{min-width:0;transition:border-color .15s}.run-card.selected{border-color:var(--blue);box-shadow:0 0 0 1px var(--blue)}.run-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.run-title{display:flex;gap:9px;align-items:flex-start;min-width:0}.run-card h3{font-size:15px;margin:0}.meta{color:var(--muted);font-size:12px;margin:3px 0 10px}.chart-button{display:block;width:100%;height:auto;border:0;border-radius:8px;background:#0c131c;padding:0;cursor:pointer;color:inherit}.chart-button:hover,.chart-button:focus{outline:2px solid var(--blue)}.hint{text-align:right;color:#60758d;font-size:11px;margin-top:4px}
details{background:var(--panel);border:1px solid var(--line);border-radius:10px;margin:9px 0;padding:10px 12px;scroll-margin-top:20px}summary{cursor:pointer;font-weight:650}.raw{max-height:600px;overflow:auto;white-space:pre-wrap;background:#080c11;border-radius:8px;padding:14px;color:#b8c7d8;font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}.empty{padding:35px;text-align:center;color:var(--muted)}
@media(max-width:700px){.page{padding:22px 14px}.comparison-row{grid-template-columns:1fr 60px}.comparison-row .track{grid-column:1/-1;grid-row:2}.run-grid{grid-template-columns:1fr}.rename-row{grid-template-columns:1fr auto}.rename-id,.name-input,.folder-select{grid-column:1/-1}.folder-row{grid-template-columns:1fr auto auto auto}}
</style>
</head>
<body><main class="page"><h1>State MCTS experiments</h1><div class="sub">Reward comparisons from <code>state_mcts_report.json</code> · generated __GENERATED_AT__</div><div id="app"></div></main>
<script>
const REPORT=__REPORT_DATA__;
const FOLDER_OPEN_STORAGE_KEY='state-mcts-folder-open-v1';
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=value=>typeof value==='number'?(Number.isInteger(value)?String(value):Math.abs(value)>=100?value.toFixed(1):value.toFixed(2)):String(value);
function folderOpenStates(){try{return JSON.parse(localStorage.getItem(FOLDER_OPEN_STORAGE_KEY)||'{}')}catch(error){return {}}}
function folderPanelKey(section,group){return `${section}:${group.id||'unfiled'}`}
function rememberFolderState(details){const states=folderOpenStates();states[details.dataset.folderKey]=details.open;try{localStorage.setItem(FOLDER_OPEN_STORAGE_KEY,JSON.stringify(states))}catch(error){/* Storage can be unavailable in restricted file mode. */}}
function badge(status){let css=status==='completed'?'good':status==='failed'||status==='interrupted'?'bad':'warn';return `<span class="badge ${css}">${esc(status||'unknown')}</span>`}
function openRaw(id){const target=document.getElementById(id);if(!target)return;target.open=true;let parent=target.parentElement;while(parent){if(parent.tagName==='DETAILS')parent.open=true;parent=parent.parentElement}target.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>target.querySelector('summary')?.focus(),250)}
function runName(run,fallback='unnamed run'){return run.display_name||fallback}
async function saveRunName(runId,inputId,statusId){const input=document.getElementById(inputId),status=document.getElementById(statusId);status.textContent='Saving…';try{const response=await fetch('/api/run-name',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({run_id:runId,display_name:input.value})});const result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);status.textContent='Saved';setTimeout(()=>location.reload(),350)}catch(error){status.textContent=location.protocol==='file:'?'Read-only file mode — run python -m state_mcts.dashboard_server':`Error: ${error.message}`;status.className='save-status bad'}}
const selectedRunIds=new Set();
function toggleRunSelection(runId,checked){if(checked)selectedRunIds.add(runId);else selectedRunIds.delete(runId);syncSelectionUi()}
function syncSelectionUi(){document.querySelectorAll('[data-select-run]').forEach(input=>{const selected=selectedRunIds.has(input.dataset.selectRun);input.checked=selected;input.closest('.run-card')?.classList.toggle('selected',selected)});const count=document.getElementById('selected-count'),button=document.getElementById('bulk-move');if(count)count.textContent=`${selectedRunIds.size} selected`;if(button)button.disabled=selectedRunIds.size===0}
function selectAllRuns(){normalizeRuns(REPORT).forEach(run=>selectedRunIds.add(run.run_id));syncSelectionUi()}
function clearRunSelection(){selectedRunIds.clear();syncSelectionUi()}
function bulkAssignSelected(){if(!selectedRunIds.size)return;const folderId=document.getElementById('bulk-folder')?.value||'',next={...assignments()};selectedRunIds.forEach(runId=>{if(folderId)next[runId]=folderId;else delete next[runId]});REPORT.dashboard_run_folders=next;render();persistFolders()}
function bulkToolbar(){return `<div class="bulk-toolbar"><strong id="selected-count">${selectedRunIds.size} selected</strong><div class="bulk-actions"><button class="folder-action" onclick="selectAllRuns()">Select all</button><button class="folder-action" onclick="clearRunSelection()">Clear</button><select class="folder-select" id="bulk-folder" aria-label="Destination folder"><option value="">Unfiled</option>${folders().map(folder=>`<option value="${esc(folder.id)}">${esc(folder.name)}</option>`).join('')}</select><button class="folder-action" id="bulk-move" onclick="bulkAssignSelected()" ${selectedRunIds.size?'':'disabled'}>Move selected</button></div></div>`}
function folders(report=REPORT){return Array.isArray(report.dashboard_folders)?report.dashboard_folders.filter(folder=>folder&&typeof folder.id==='string'&&typeof folder.name==='string'):[]}
function assignments(report=REPORT){return report.dashboard_run_folders&&typeof report.dashboard_run_folders==='object'?report.dashboard_run_folders:{}}
function alphabeticalRunLabel(run){return String(run.display_name||(run.selected_models||[]).join(' + ')||Object.keys(run.evaluations||{})[0]||'baseline')}
function baseOrderedRuns(report){const runs=Array.isArray(report.runs)?report.runs:[{run_id:'legacy-run',status:'completed',selected_models:report.selected_models||[],training_metrics:report.training_metrics||{},evaluations:report.evaluations||{},settings:report.settings||{}}];return [...runs].sort((first,second)=>alphabeticalRunLabel(first).localeCompare(alphabeticalRunLabel(second),undefined,{numeric:true,sensitivity:'base'})||String(first.run_id).localeCompare(String(second.run_id)))}
function normalizeRuns(report){const ordered=baseOrderedRuns(report),assigned=assignments(report),result=[],seen=new Set();folders(report).forEach(folder=>ordered.forEach(run=>{if(assigned[run.run_id]===folder.id&&!seen.has(run.run_id)){result.push(run);seen.add(run.run_id)}}));ordered.forEach(run=>{if(!seen.has(run.run_id)){result.push(run);seen.add(run.run_id)}});return result}
function folderName(run,report=REPORT){const id=assignments(report)[run.run_id],folder=folders(report).find(candidate=>candidate.id===id);return folder?folder.name:'Unfiled'}
async function persistFolders(){try{const response=await fetch('/api/folders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({folders:folders(),run_folders:assignments()})});const result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);setTimeout(()=>location.reload(),150)}catch(error){alert(location.protocol==='file:'?'Folders are read-only in file mode. Run python -m state_mcts.dashboard_server.':`Could not save folders: ${error.message}`);location.reload()}}
function createFolder(){const name=prompt('Folder name');if(!name||!name.trim())return;REPORT.dashboard_folders=folders().concat([{id:`folder-${Date.now().toString(36)}`,name:name.trim().slice(0,100)}]);persistFolders()}
function renameFolder(index,inputId){const list=folders().map(folder=>({...folder})),input=document.getElementById(inputId),name=input?.value.trim();if(!name)return alert('Folder name cannot be empty.');list[index].name=name.slice(0,100);REPORT.dashboard_folders=list;persistFolders()}
function moveFolder(index,delta){const list=folders().map(folder=>({...folder})),target=index+delta;if(target<0||target>=list.length)return;[list[index],list[target]]=[list[target],list[index]];REPORT.dashboard_folders=list;render();persistFolders()}
function deleteFolder(index){const list=folders().map(folder=>({...folder})),folder=list[index];if(!folder||!confirm(`Delete folder “${folder.name}”? Its runs will move to Unfiled.`))return;list.splice(index,1);REPORT.dashboard_folders=list;const next={...assignments()};Object.keys(next).forEach(runId=>{if(next[runId]===folder.id)delete next[runId]});REPORT.dashboard_run_folders=next;render();persistFolders()}
function assignRunFolder(runId,folderId){const next={...assignments()};if(folderId)next[runId]=folderId;else delete next[runId];REPORT.dashboard_run_folders=next;render();persistFolders()}
function folderManager(){const list=folders();return `<div class="folder-manager"><div class="folder-toolbar"><div><strong>Run folders</strong><div class="models">Folder order is shared by every dashboard section.</div></div><button class="folder-action" onclick="createFolder()">+ New folder</button></div>${list.length?list.map((folder,index)=>{const inputId=`folder-name-${index}`;return `<div class="folder-row"><input class="folder-input" id="${inputId}" maxlength="100" value="${esc(folder.name)}" onkeydown="if(event.key==='Enter')renameFolder(${index},'${inputId}')"><button class="folder-action" onclick="renameFolder(${index},'${inputId}')">Save</button><span><button class="folder-action" onclick="moveFolder(${index},-1)" title="Move folder up">↑</button> <button class="folder-action" onclick="moveFolder(${index},1)" title="Move folder down">↓</button></span><button class="folder-action danger" onclick="deleteFolder(${index})">Delete</button></div>`}).join(''):'<div class="empty">No folders yet. All runs are currently Unfiled.</div>'}</div>`}
function evaluations(runs){let result=[];runs.forEach((run,runIndex)=>Object.entries(run.evaluations||{}).forEach(([name,evaluation],evaluationIndex)=>result.push({run,runIndex,evaluationIndex,name,evaluation,rawId:`raw-run-${runIndex}`})));return result}
function comparisonRow(item,maxScale){const e=item.evaluation,mean=e.mean_reward||0,min=e.min_reward??mean,max=e.max_reward??mean,barWidth=Math.max(0,Math.min(100,mean/maxScale*100)),left=Math.max(0,Math.min(100,min/maxScale*100)),right=Math.max(left,Math.min(100,max/maxScale*100));return `<button class="comparison-row" onclick="openRaw('${item.rawId}')"><div><div class="run-name">${esc(runName(item.run,item.name))}</div><div class="models">${esc(folderName(item.run))} · ${esc(item.name)} · ${esc((item.run.selected_models||[]).join(' + ')||'baseline')} · ${esc(item.run.run_id)}</div></div><div class="track"><div class="mean-bar" style="width:${barWidth}%"></div><div class="range" style="left:${left}%;width:${right-left}%" title="range ${fmt(min)}–${fmt(max)}"></div></div><div class="score">${fmt(mean)}</div></button>`}
function episodeBars(item,maxScale=500){const values=item.evaluation.episode_rewards||[],mean=item.evaluation.mean_reward||0;if(!values.length)return '<div class="empty">No episode rewards recorded yet.</div>';const width=660,height=205,left=44,right=12,top=15,bottom=31,plotW=width-left-right,plotH=height-top-bottom,scale=Math.max(maxScale,...values,1),slot=plotW/values.length,gap=Math.max(1,slot*.18),barWidth=Math.max(2,slot-gap),y=value=>top+plotH-value/scale*plotH;const grid=[0,.25,.5,.75,1].map(f=>{const value=scale*f,yp=y(value);return `<line x1="${left}" y1="${yp}" x2="${width-right}" y2="${yp}" stroke="#29394d"/><text x="${left-7}" y="${yp+4}" text-anchor="end" fill="#71849b" font-size="10">${Math.round(value)}</text>`}).join('');const bars=values.map((value,index)=>{const x=left+index*slot+gap/2,yp=y(value),barHeight=top+plotH-yp;return `<rect x="${x.toFixed(2)}" y="${yp.toFixed(2)}" width="${barWidth.toFixed(2)}" height="${barHeight.toFixed(2)}" rx="2" fill="#62b0ff"><title>Episode ${index+1}: ${fmt(value)}</title></rect>${values.length<=30?`<text x="${(x+barWidth/2).toFixed(2)}" y="${height-12}" text-anchor="middle" fill="#60758d" font-size="9">${index+1}</text>`:''}`}).join('');const meanY=y(mean);return `<button class="chart-button" onclick="openRaw('${item.rawId}')" aria-label="Open exact run JSON"><svg viewBox="0 0 ${width} ${height}" role="img">${grid}${bars}<line x1="${left}" y1="${meanY}" x2="${width-right}" y2="${meanY}" stroke="#55d69e" stroke-width="2" stroke-dasharray="6 4"/><text x="${width-right-3}" y="${meanY-5}" text-anchor="end" fill="#55d69e" font-size="10">mean ${fmt(mean)}</text><text x="${left+plotW/2}" y="${height-2}" text-anchor="middle" fill="#71849b" font-size="10">evaluation episode</text></svg></button><div class="hint">Click chart to open exact JSON ↓</div>`}
function runTile(run,index,items){const runItems=items.filter(item=>item.run===run);return `<article class="run-card" data-run-id="${esc(run.run_id)}"><div class="run-head"><div class="run-title"><input class="run-select" type="checkbox" data-select-run="${esc(run.run_id)}" aria-label="Select ${esc(runName(run,run.run_id))}" onchange="toggleRunSelection('${esc(run.run_id)}',this.checked)"><div><h3>${esc(runName(run,runItems[0]?.name||'run'))}</h3><div class="meta">${esc(folderName(run))} · ${esc((run.selected_models||[]).join(' + ')||'baseline')} · ${esc(run.run_id)}</div></div></div>${badge(run.status)}</div>${runItems.map(item=>`<div class="meta">${esc(item.name)} · ${(item.evaluation.episode_rewards||[]).length} episodes</div>${episodeBars(item)}`).join('')}</article>`}
function runGroups(runs){const assigned=assignments(),groups=folders().map(folder=>({id:folder.id,name:folder.name,runs:runs.filter(run=>assigned[run.run_id]===folder.id)}));groups.push({id:'',name:'Unfiled',runs:runs.filter(run=>!folders().some(folder=>folder.id===assigned[run.run_id]))});return groups}
function folderPanel(section,group,content,emptyText='No runs in this folder.'){const key=folderPanelKey(section,group),isOpen=folderOpenStates()[key]===true;return `<details class="folder-block" data-folder-key="${esc(key)}" ${isOpen?'open':''} ontoggle="rememberFolderState(this)"><summary class="folder-summary">${esc(group.name)} <span class="folder-badge">${group.runs.length} run${group.runs.length===1?'':'s'}</span></summary>${content||`<div class="empty">${esc(emptyText)}</div>`}</details>`}
function groupedTiles(runs,items){return runGroups(runs).map(group=>folderPanel('rewards',group,group.runs.length?`<div class="run-grid">${group.runs.map(run=>runTile(run,runs.indexOf(run),items)).join('')}</div>`:'' )).join('')}
function renameRow(run,index,folderOptions){const inputId=`run-name-${index}`,statusId=`run-name-status-${index}`,selected=assignments()[run.run_id]||'';return `<div class="rename-row"><input class="run-select" type="checkbox" data-select-run="${esc(run.run_id)}" aria-label="Select ${esc(runName(run,run.run_id))}" onchange="toggleRunSelection('${esc(run.run_id)}',this.checked)"><div class="rename-id" title="${esc(run.run_id)}">${esc(run.run_id)}</div><input class="name-input" id="${inputId}" maxlength="100" value="${esc(run.display_name||'')}" placeholder="Add a descriptive run name" onkeydown="if(event.key==='Enter')saveRunName('${esc(run.run_id)}','${inputId}','${statusId}')"><select class="folder-select" aria-label="Folder for ${esc(run.run_id)}" onchange="assignRunFolder('${esc(run.run_id)}',this.value)"><option value="">Unfiled</option>${folderOptions.map(folder=>`<option value="${esc(folder.id)}" ${selected===folder.id?'selected':''}>${esc(folder.name)}</option>`).join('')}</select><button class="save-name" onclick="saveRunName('${esc(run.run_id)}','${inputId}','${statusId}')">Save name</button><span class="save-status" id="${statusId}"></span></div>`}
function renameControls(runs){const folderOptions=folders();return runGroups(runs).map(group=>folderPanel('names',group,group.runs.length?`<div class="rename-list">${group.runs.map(run=>renameRow(run,runs.indexOf(run),folderOptions)).join('')}</div>`:'' )).join('')}
function groupedComparisons(runs,items,scale){return runGroups(runs).map(group=>{const groupItems=items.filter(item=>group.runs.includes(item.run));return folderPanel('comparisons',group,groupItems.length?`<div class="comparison">${groupItems.map(item=>comparisonRow(item,scale)).join('')}</div>`:'','No completed evaluations in this folder.')}).join('')}
function rawConfigurations(runs){return runGroups(runs).map(group=>folderPanel('configurations',group,group.runs.map(run=>{const index=runs.indexOf(run);return `<details id="raw-run-${index}"><summary tabindex="-1">${esc(runName(run,Object.keys(run.evaluations||{})[0]||'run'))} · ${esc(run.run_id)}</summary><pre class="raw">${esc(JSON.stringify(run,null,2))}</pre></details>`}).join(''),'No run configurations in this folder.')).join('')}
function render(){const runs=normalizeRuns(REPORT),items=evaluations(runs),means=items.map(item=>item.evaluation.mean_reward).filter(Number.isFinite),best=means.length?Math.max(...means):null,scale=Math.max(500,...means,1);document.getElementById('app').innerHTML=`<div class="callout">Create folders, assign runs below, and order folders with ↑/↓. Click any folder heading to expand or collapse it. Runs are automatically sorted alphabetically by display name inside each folder; the same order controls editable names, mean comparison, reward graphs, and full configurations. Use the checkboxes to move several runs together. Saving requires the local dashboard server.</div><div class="cards"><div class="card"><h3>Recorded runs</h3><div class="big">${runs.length}</div></div><div class="card"><h3>Folders</h3><div class="big">${folders().length}</div></div><div class="card"><h3>Evaluations</h3><div class="big">${items.length}</div></div><div class="card"><h3>Best mean reward</h3><div class="big">${best===null?'—':fmt(best)}</div></div><div class="card"><h3>Run order</h3><div class="big">A → Z</div></div></div><h2>Folder organization</h2>${folderManager()}<h2>Bulk run actions</h2>${bulkToolbar()}<h2>Editable run names and folder assignments</h2>${renameControls(runs)}<h2>Mean reward comparison</h2>${items.length?groupedComparisons(runs,items,scale):'<div class="empty">No completed evaluations yet.</div>'}<h2>Reward graphs</h2>${groupedTiles(runs,items)}<h2>Full run configurations and raw data</h2>${rawConfigurations(runs)}<details><summary>Complete state_mcts_report.json</summary><pre class="raw">${esc(JSON.stringify(REPORT,null,2))}</pre></details>`;syncSelectionUi()}
render();
</script>
</body>
</html>"""


def load_state_report(artifact_dir: Path):
    report_path = artifact_dir / "state_mcts_report.json"
    if not report_path.exists():
        raise FileNotFoundError(f"Missing state MCTS report: {report_path}")
    return json.loads(report_path.read_text(encoding="utf-8"))


def generate_dashboard(artifact_dir, output_path):
    artifact_dir = Path(artifact_dir)
    output_path = Path(output_path)
    report = load_state_report(artifact_dir)
    embedded = json.dumps(report, separators=(",", ":")).replace("<", "\\u003c")
    html = HTML_TEMPLATE.replace("__REPORT_DATA__", embedded).replace(
        "__GENERATED_AT__", datetime.now(timezone.utc).isoformat()
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")
    return 1


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--artifact-dir", default="artifacts/state_mcts")
    parser.add_argument(
        "--output", default="artifacts/state_mcts/diagnostics_dashboard.html"
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    generate_dashboard(args.artifact_dir, args.output)
    print(f"state MCTS dashboard: {args.output}")
